# display a robot
print("############")
print("# /\   /\  #")
print("#          #")
print("#   ----   #")
print("############")
print("    |  |   ")
print("    |  |    ")
print(" -----------")
print(" |          |")
print(" |          |")
print(" |          |")
print(" |          |")
print(" ------------")
print("   | |   | |")
print("   | |   | |")
print("   | |   | |")
print("  ----- -----")